# Generated by Django 5.0.4 on 2024-05-09 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_data', models.CharField(max_length=20)),
                ('description_data', models.CharField(max_length=50)),
                ('date_data', models.DateField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.reg')),
            ],
        ),
    ]
